import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import "antd/dist/reset.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#000000",
  icons: [
    { rel: "icon", url: "/favicon.ico" },
    // { rel: "apple-touch-icon", url: "/icons/apple-icon.png" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
